
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
server:
  port: 8081
spring:
  profiles: server0
  application:
    name: costumer
  cloud:
    config:
      uri: http://localhost:8888
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:costumer
    h2:
      console:
        enabled: true
  hateoas:
    use-hal-as-default-json-media-type: false
    
---
spring:
  profiles: server1
server:
  port: 8082
---
spring:
  profiles: server2
server:
  port: 8083

#H2
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:costumer

#actuator
#management.endpoints.web.exposure.include=*

# cloud
#spring.application.name=costumer
#spring.cloud.config.uri=http://localhost:8888
#server.port=8081

# jpa
#spring.jpa.show-sql=true
#spring.datasource.url= jdbc:mysql://localhost:3306/greendogdelivery
#spring.datasource.username=greendogdelivery
#spring.datasource.password=greendogdelivery
#spring.jpa.hibernate.ddl-auto=none

#rest
#spring.data.rest.base-path=/api

# Hypermedia As The Engine Of Application State
#spring.hateoas.use-hal-as-default-json-media-type=false

# permite acesso ao Actuator
#management.security.enabled=false
