management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
server:
  port: 8082
spring:
  profiles: server0
  application:
    name: costumer
  cloud:
    config:
      uri: http://localhost:8888
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:costumer
    h2:
      console:
        enabled: true
  hateoas:
    use-hal-as-default-json-media-type: false
    
---
spring:
  profiles: server1
server:
  port: 8083

---
spring:
  profiles: server2
server:
  port: 8084
